REFRESH MATERIALIZED VIEW gar_reestr_objects;
REFRESH MATERIALIZED VIEW gar_houses;
REFRESH MATERIALIZED VIEW gar_apartments;
REFRESH MATERIALIZED VIEW gar_carplaces;
REFRESH MATERIALIZED VIEW gar_rooms;
REFRESH MATERIALIZED VIEW gar_steads;
